{
 "title": "Application Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency (p99 response time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(http_requests_total{status=~\"503|500\"}[5m]) / rate(http_requests_total[5m])) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1h])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}